/*1*/
ALTER TABLE JUGADOR 
ADD COLUMN TELEFONO varchar(9);
/*2*/
INSERT INTO JUGADOR(TELEFONO)
VALUE("120") WHERE EQUIPO_JUGADOR="ESPAÑA";

INSERT INTO JUGADOR(TELEFONO)
VALUE("90") WHERE EQUIPO_JUGADOR="ARGENTINA";

INSERT INTO JUGADOR(TELEFONO)
VALUE("100") WHERE EQUIPO_JUGADOR="BRASIL";

INSERT INTO JUGADOR(TELEFONO)
VALUE("110") WHERE EQUIPO_JUGADOR!="ALEMANIA" AND "FRANCIA" AND "ITALIA";

ALTER TABLE JUGADOR 
ADD COLUMN TIPO_JUGADOR varchar(10);

INSERT INTO JUGADOR(TIPO_JUGADOR)
VALUE("ESPAÑOL") WHERE TELEFONO<111;

INSERT INTO JUGADOR(TIPO_JUGADOR)
VALUE("EXTRANJERO") WHERE TELEFONO>111 OR IS NULL;
/*3*/
SELECT DISTINCT NOMBRE_JUG FROM JUGAR WHERE MIN_JUGAR>45;
/*4*/
SELECT * FROM JUGADOR WHERE TIPO_JUGADOR="EXTRANJERO";
/*5*/
SELECT * FROM JUGADOR WHERE NOMBRE LIKE '%[aeiou]';
/*6*/
INSERT INTO JUGADOR (NOMBRE, EQUIPO_JUGADOR)
VALUES("XOJE","ESPAÑA");
/*7*/
INSERT INTO PARTIDO (EQUIPO_L,EQUIPO_V,FECHA,HORA,SEDE,RESULTADO_L,RESULTADO_V,ASISTENCIA)
VALUES("ESPAÑA","FRANCIA",'05/01/2018',NULL,NULL,3,5,NULL);
--SELECT * FROM PARTIDO WHERE FECHA='05/01/2018';
/*8*//*Mucho por revisar*/
INSERT INTO JUGAR (NOMBRE_JUG,EQUIPO_L_PART,EQUIPO_V_PART)
SELECT "XOJE",/*ns*/,/*ns*/,/*60 ns*/
FROM PARTIDO WHERE EQUIPO_L="ESPAÑA" OR EQUIPO_V="ESPAÑA" AND NOT (EQUIPO_L="ESPAÑA" AND EQUIPO_V="FRANCIA" AND fecha="05/01/2018");
/*9*/
ALTER TABLE PARTIDO 
ADD COLUMN HORA2 varchar(8);
INSERT INTO PARTIDO (HORA,HORA2)
VALUE (NULL,SELECT HORA FROM PARTIDO);
/*10*/
UPDATE JUGADOR
SET FECHA_NAC='15/02/1994'
WHERE NOMBRE="JULIO DOS SANTOS";

UPDATE JUGADOR
SET FECHA_NAC='15/06/1993'
WHERE NOMBRE="LAUREN";

UPDATE JUGADOR
SET FECHA_NAC='06/02/1995'
WHERE NOMBRE="LUCAS BARRIOS";

UPDATE JUGADOR
SET FECHA_NAC='01/09/1995'
WHERE NOMBRE="LUIS MARIN";

SELECT * FROM JUGADOR WHERE FECHA_NAC="__/02/____";
/*11*/
SELECT NOMBRE FROM JUGADOR 
WHERE FECHA_NAC IS NOT NULL
ORDER BY NOMBRE;